name: Private CL build on Windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER="cl"
        -DCMAKE_BUILD_TYPE="Release"
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config "Release"

    - name: Get last commit date
      id: getdate
      shell: bash
      run: |
        get_date=$(git log --pretty=format:"%cs" -1)
        echo "last_commit_date=$get_date" >> "$GITHUB_OUTPUT"


    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: "mmd7_win_cl-${{ steps.getdate.outputs.last_commit_date }}"
        path: build/Release/multimarkdown.exe
        if-no-files-found: warn
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
